# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style) in "
style = "bold dimmed green"
disabled = true
